import { MODERN_PALETTE } from "@/components/menu-render/modern/modern-palette";

export interface ModernFooterProps {
  address?: string;
  phone?: string;
  /** Small print under the contact line, e.g. "Prices include VAT". */
  note?: string;
  /**
   * Pre-rendered QR as a data URI. Undefined whenever there's nothing to
   * point at — an unpublished menu has no public URL, and a QR that
   * resolves nowhere is worse than no QR. Generated by the caller (which
   * knows the slug), not here, so this component stays render-only.
   */
  qrDataUri?: string;
  qrLabel: string;
}

/**
 * Address / phone on the left, QR on the right. Renders nothing at all when
 * it would be empty — a menu with no venue contacts and no published URL
 * gets no footer band, rather than an empty dark stripe.
 */
export function ModernFooter({ address, phone, note, qrDataUri, qrLabel }: ModernFooterProps) {
  const contactLine = [address, phone].filter(Boolean).join(" · ");
  if (!contactLine && !note && !qrDataUri) {
    return null;
  }

  return (
    <div
      data-testid="modern-footer"
      style={{
        backgroundColor: MODERN_PALETTE.footer,
        borderTop: `1px solid ${MODERN_PALETTE.footerBorder}`,
        padding: "12px 26px",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 16,
      }}
    >
      <div>
        {contactLine && (
          <p
            data-testid="modern-footer-contact"
            style={{ margin: 0, fontSize: 11, color: MODERN_PALETTE.footerText }}
          >
            {contactLine}
          </p>
        )}
        {note && (
          <p style={{ margin: "2px 0 0", fontSize: 11, color: MODERN_PALETTE.textFaint }}>{note}</p>
        )}
      </div>

      {qrDataUri && (
        <div style={{ display: "flex", alignItems: "center", gap: 9, flexShrink: 0 }}>
          <span style={{ fontSize: 10, color: MODERN_PALETTE.footerText, textAlign: "end" }}>
            {qrLabel}
          </span>
          {/* eslint-disable-next-line @next/next/no-img-element -- a generated data: URI, nothing for next/image to optimize */}
          <img
            data-testid="modern-footer-qr"
            src={qrDataUri}
            alt=""
            style={{
              width: 38,
              height: 38,
              borderRadius: 5,
              backgroundColor: MODERN_PALETTE.qrPlate,
            }}
          />
        </div>
      )}
    </div>
  );
}
